version: '3.8'

services:
  wikijs:
    image: requarks/wiki:2
    depends_on:
      - db
    ports:
      - "80:3000"
    environment:
      # Personalize essas variáveis de ambiente conforme necessário
      DB_TYPE: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: example
      DB_NAME: wiki
      WIKI_ADMIN_EMAIL: admin@example.com
      WIKI_ADMIN_PASSWORD: admin
      WIKI_SITE_NAME: "Meu WikiJS"
      WIKI_SITE_URL: "http://localhost:80"
      WIKI_PRIVACY_POLICY_URL: "https://example.com/privacy"
      WIKI_TERMS_OF_USE_URL: "https://example.com/terms"
      NODE_ENV: production
    volumes:
      - wikijs-data:/var/wiki/data
      - wikijs-backups:/var/wiki/backups

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wiki
    volumes:
      - db-data:/var/lib/mysql

volumes:
  wikijs-data:
  wikijs-backups:
  db-data:
